@UserManagementAPI_HostAddress = http://localhost:5224

### Get a list of users
GET {{UserManagementAPI_HostAddress}}/api/users
Accept: application/json

### Get user by ID
GET {{UserManagementAPI_HostAddress}}/api/users/{d5f9a497-6d1b-47f2-b2c9-4ec9f72d6b32}
Accept: application/json

### Create a new user
POST {{UserManagementAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "id": "d5f9a497-6d1b-47f2-b2c9-4ec9f72d6b32",
  "name": "Иван Иванов",
  "email": "ivan@example.com"
}
### Create a new user (unique ID and Email)
POST {{UserManagementAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "id": "a3b7d9f0-1234-4ef2-9876-3c92b5e8d123",
  "name": "Анна Смирнова",
  "email": "anna.smirnova@example.com"
}

### Create a new user (different unique ID and Email)
POST {{UserManagementAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "id": "5cbe3a2f-4567-4ef9-abcd-9d23b7c45678",
  "name": "Петр Сидоров",
  "email": "petr.sidorov@example.com"
}

### Trying to create a user with an existing Email (should return 400 Bad Request)
POST {{UserManagementAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "id": "7f3e1d90-7890-4abc-def1-5b6a7c89abcd",
  "name": "Иван Иванов",
  "email": "ivan@example.com"
}

###Trying to create a user with an empty ID (should return 400 Bad Request)
POST {{UserManagementAPI_HostAddress}}/api/users
Content-Type: application/json

{
  "id": "",
  "name": "Алексей Кузнецов",
  "email": "alexey.kuznetsov@example.com"
}
### Update user information
PUT {{UserManagementAPI_HostAddress}}/api/users/{7f3e1d90-7890-4abc-def1-5b6a7c89abcd}
Content-Type: application/json

{
  "name": "Иван Иванов",
  "email": "ivan.updated@example.com"
}

### Delete user
DELETE {{UserManagementAPI_HostAddress}}/api/users/{d5f9a497-6d1b-47f2-b2c9-4ec9f72d6b32}
